apiVersion: v1
kind: Service
metadata:
  name: selenium
spec:
  ports:
  - name: selenium
    port: 4444
    targetPort: 4444
    protocol: TCP
  - name: chrome
    port: 5900
    targetPort: 5900
    protocol: TCP
  selector:
    app: daf-metabase-cacher-be
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: daf-metabase-cacher-be-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: daf-metabase-cacher-be
    spec:
      containers:
        - name: selenium-node-chrome
          image: selenium/node-chrome-debug:2.53.0
          ports:
            - containerPort: 5900 
          env:
            - name: HUB_PORT_4444_TCP_ADDR 
              value: "localhost"
            - name: HUB_PORT_4444_TCP_PORT 
              value: "4444"
            - name: NODE_MAX_INSTANCES
              value: "60"
            - name: NODE_MAX_SESSION
              value: "60"
        - name: selenium
          image: selenium/hub
          ports:
            - containerPort: 4444
          env:
            - name: GRID_MAX_SESSION
              value: "200"
            - name: GRID_BRIWSER_TIMEOUT
              value: "100000"
            - name: GRID_TIMEOUT
              value: "90000"
            - name: GRID_NEW_SESSION_WAIT_TIMEOUT
              value: "300000"
